platform :ios, '8.0'
use_frameworks!

pod 'MBProgressHUD'
pod 'hpple'
pod 'FMDB’
pod 'Alamofire'
pod 'AsyncSwift'
pod 'HanekeSwift'
pod 'M13ProgressSuite'
pod 'Realm'
pod 'RealmSwift'
pod 'SDWebImage'
pod 'JDStatusBarNotification'
pod 'JTMaterialTransition'
pod 'TTTAttributedLabel'
pod 'ReactiveCocoa'
